# Book settings
title: The Educator’s Guide to Technology Infrastructure for Data 8
author: UC Berkeley Data Science Education Program
logo: 'images/data8.png'

latex:
  latex_documents:
    targetname: book.tex
